import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  Sidebar,
  SidebarBody,
  SidebarLink,
} from "../components/sidebar"; // Removed useSidebar import
import {
  // Home, // Home is unused now, can be removed later if desired
  Settings,
  FilePenLine,
  Search,
  FolderKanban,
} from "lucide-react";
import { ScrollArea } from "../components/ui/scroll-area"; // Import ScrollArea

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Removed OpenOnly helper component

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Sidebar> {/* SidebarProvider is inside Sidebar */}
          {/* Changed flex direction for responsiveness */}
          <div className="flex flex-col md:flex-row h-screen">
            {/* SidebarBody renders DesktopSidebar (md+) and MobileSidebar (<md) */}
            <SidebarBody className="border-r border-neutral-200 dark:border-neutral-700 flex-shrink-0 md:h-full"> {/* Ensure full height on md+ */}
              {/* This content will be rendered inside DesktopSidebar and MobileSidebar */}
              {/* Content structure remains, but conditional rendering is moved to sidebar.tsx */}
              <div className="flex flex-col h-full p-4 overflow-hidden">
                {/* Top Static Section */}
                <div>
                  <SidebarLink
                    link={{
                      label: "New Document",
                      href: "/",
                      icon: <FilePenLine className="w-4 h-4" />,
                    }}
                  />
                  {/* Search Bar JSX moved to sidebar.tsx */}
                  <SidebarLink
                    link={{
                      label: "Docs",
                      href: "/docs",
                      icon: <FolderKanban className="w-4 h-4" />,
                    }}
                  />
                </div>

                {/* Middle Scrollable History Section JSX moved to sidebar.tsx */}

                {/* Bottom Static Section */}
                <div className="mt-auto">
                  <div className="flex items-center gap-2 mb-2 p-2 rounded hover:bg-neutral-200 dark:hover:bg-neutral-700 cursor-pointer">
                    <div className="w-6 h-6 bg-neutral-300 dark:bg-neutral-600 rounded-full flex-shrink-0"></div> {/* Profile Placeholder */}
                    {/* User Name Span moved to sidebar.tsx */}
                  </div>
                  <SidebarLink
                    link={{
                      label: "Settings",
                      href: "/settings",
                      icon: <Settings className="w-4 h-4" />,
                    }}
                  />
                </div>
              </div>
            </SidebarBody>
            {/* Main Content Area */}
            <main className="flex-1 overflow-y-auto">{children}</main>
          </div>
        </Sidebar>
      </body>
    </html>
  );
}
